const BUTTON = 'button';
const CARD = 'card';
const CHECKBOX = 'checkbox';
const COMPONENTS = 'components';
const DIALOG = 'dialog';
const DRAWER = 'drawer';
const FAB = 'fab';
const ICON_TOGGLE = 'icon-toggle';
const INSTALLATION = 'installation';
const LAYOUT_GRID = 'layout-grid';
const LINEAR_PROGRESS = 'linear-progress';
const LIST = 'list';
const RADIO = 'radio';
const ROOT = '/';
const SELECT = 'select';
const SNACKBAR = 'snackbar';
const SWITCH = 'switch';
const TEXT_FIELD = 'text-field';
const TOOLBAR = 'toolbar';
const TYPOGRAPHY = 'typography';

export const join = (...sections) => `${ROOT}${(sections).join('/')}`;

export const componentButton = () => join(COMPONENTS, BUTTON);
export const componentCard = () => join(COMPONENTS, CARD);
export const componentCheckbox = () => join(COMPONENTS, CHECKBOX);
export const componentDialog = () => join(COMPONENTS, DIALOG);
export const componentDrawer = () => join(COMPONENTS, DRAWER);
export const componentFab = () => join(COMPONENTS, FAB);
export const componentIconToggle = () => join(COMPONENTS, ICON_TOGGLE);
export const componentLayoutGrid = () => join(COMPONENTS, LAYOUT_GRID);
export const componentLinearProgress = () => join(COMPONENTS, LINEAR_PROGRESS);
export const componentList = () => join(COMPONENTS, LIST);
export const componentRadio = () => join(COMPONENTS, RADIO);
export const components = () => join(COMPONENTS);
export const componentSelect = () => join(COMPONENTS, SELECT);
export const componentSnackbar = () => join(COMPONENTS, SNACKBAR);
export const componentSwitch = () => join(COMPONENTS, SWITCH);
export const componentTextField = () => join(COMPONENTS, TEXT_FIELD);
export const componentToolbar = () => join(COMPONENTS, TOOLBAR);
export const componentTypography = () => join(COMPONENTS, TYPOGRAPHY);
export const installation = () => join(INSTALLATION);
export const root = () => join();
